### ISSUE TITLE
bug: only use one column on desktop single idea view

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#690] opened 2020-11-04 22:14 UTC
seems to be a weird 4 column layout bug compressing large texts on desktop view

Example:
https://www.dailyidea.com/i/3dgdlr/better-airbnb-chrome-extension

Screenshot:
https://monosnap.com/file/6xbWllbhbHxE7RhUs7JlZQIkXjPggc

(edit: appears to also happen on mobile)

**Comment by vedmant** [comment] 2020-11-06 10:05
@ezl looks like duplicate of #689 ?

**Comment by ezl** [comment] 2020-11-07 01:53
oops, yes, was duplicate. when i created the ticket, github gave an error, so i didn't realize it had been created. 😇

**Closed** 2020-11-15 13:59 UTC
