### ISSUE TITLE
"Saving" an Idea won't increase the counter

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#759] opened 2020-11-29 12:58 UTC
Steps:
- I click on the "Save" icon of any idea. The counter doesn't go up.
![image](https://user-images.githubusercontent.com/16639403/100542554-f7207400-324a-11eb-8ba8-7062d504a231.png)

**Comment by ikosovec** [comment] 2020-12-01 19:35
This is not working correctly.
I get to a random idea from the Explore page.
Current state:
![image](https://user-images.githubusercontent.com/16639403/100787752-65fcf900-3414-11eb-9c48-c2f5224974a5.png)
I click on "Save" - this is correct:
![image](https://user-images.githubusercontent.com/16639403/100787786-7319e800-3414-11eb-8188-0b268a546ffe.png)
I click on "Unsave" - it goes back to "0", although we started with "1!:
![image](https://user-images.githubusercontent.com/16639403/100787828-81680400-3414-11eb-87f9-afcba2b76b7f.png)

So a bit more:
After I did all of the above, I go to the profile (https://beta.dailyidea.com/profile/vedmant). The idea is shown like this:
![image](https://user-images.githubusercontent.com/16639403/100787918-a52b4a00-3414-11eb-9a31-11e3dc7d0486.png)
I click on "Unsave":
![image](https://user-images.githubusercontent.com/16639403/100787957-b5dbc000-3414-11eb-8ded-bdb2b25dcc25.png)
I click on "Save":
![image](https://user-images.githubusercontent.com/16639403/100787983-be33fb00-3414-11eb-9215-2e10665211f6.png)

**Comment by ikosovec** [comment] 2020-12-04 14:05
Still not behaving correctly.
Steps:
- I go to explore
- Click on Save - it increases the counter (OK)
- Go to profile of the idea author - the "Saved" icon is highlighted as saved, but the counter is not going up (not OK)
- Click on "view idea" - the "Saved" icon is highlighted as saved, but the counter is not going up (not OK)

-- Next test --
Steps:
- I go to profile
- Pick a random idea
- Press "Save" - counter goes up (OK)
- Click on "view idea" - counter is on 1 (OK)
- "Unsave" - goes back to 0 both on profile and on "view idea" (OK)
- "Save" again
- Go to "Explore"
- The "Save" icon is filled, but the counter is on 0 (not OK)
- "Unsave" - > "Save" again - counter goes up to 1 (OK)
- Go back to profile - counter is on 0 (not OK)

**Comment by vedmant** [comment] 2020-12-08 13:54
> Go to profile of the idea author - the "Saved" icon is highlighted as saved, but the counter is not going up (not OK)
> Click on "view idea" - the "Saved" icon is highlighted as saved, but the counter is not going up (not OK)

This works ok for me.

> I go to profile
Pick a random idea
Press "Save" - counter goes up (OK)
Click on "view idea" - counter is on 1 (OK)
"Unsave" - goes back to 0 both on profile and on "view idea" (OK)
"Save" again
Go to "Explore"
The "Save" icon is filled, but the counter is on 0 (not OK)

Yes, I can reproduce this, it's due to caching of explore page, I'll make it update cache.

But I can't reproduce this part:

> "Unsave" - > "Save" again - counter goes up to 1 (OK)
Go back to profile - counter is on 0 (not OK)

One problem I see for both save and like is that on explore page ideas are cached, so when idea is liked or saved on profile page, on explore page counts are not updated. I'll fit it now.

**Comment by ikosovec** [comment] 2020-12-09 18:10
The caching issue looks like it's fixed.

> This works ok for me.
I recorded a video to show you the behaviour. New anonymous browser, fresh log in.
https://monosnap.com/file/7alCF15v3nHwpNvYUQWLmzdXRRiv8m

**Comment by vedmant** [comment] 2020-12-10 10:23
@ikosovec Ok, should be fixed now (published on beta in 10 mins)

**Closed** 2020-12-11 12:10 UTC
Labels: bug, front-end
