### ISSUE TITLE
#17. single idea page: what happens when an idea is saved? (A) currently getting the bookmark icon stays the same color and doesn't change to a saved state (B) how can i view my saved ideas? right now other than the toast message that says "idea saved" i can't tell if anything is happening. and i can't tell if anything is actually saved

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#73] opened 2019-11-04 05:31 UTC

**Comment by patelravi** [comment] 2019-11-04 09:32
We discussed and decided earlier to postpond the api development for save idea, once we implement the apis, we can make it functional.

**Comment by aldarund** [comment] 2019-11-14 20:11
@ezl please change ticket to proper one about save idea if still need it or close :)

**Comment by aldarund** [comment] 2019-11-14 20:32
@ezl Actually its dupe of #17 . Feel free to edit that instead

**Closed** 2019-11-14 20:33 UTC
Labels: enhancement
